command/execute_command.go
db/db.go
interfaces/interfaces.go
log/log.go
log/log_test.go
main.go
server/server.go
server/single_server_test.go
server/statemachine.go

Pending:
- ~~[ ] Normalize log messages (i.e. start all with capital letter, s/unable/failed, etc.)~~
- ~~[ ] Log to stderr when it comes to error logs (ignore if writing to log file)~~
Pull request powered by [oscillatingworks](http://oscillating.works).

Deprecate log4go and fix gometalinter errors

---

cmd/rqlited/main.go
http/service.go
http/service_test.go

This function may be useful for leader-redirection.

Move URL normalization to http package

---

cmd/rqlite/query.go

fix bug for rqlite-cli query: results should be a slice instead of array

---

CHANGELOG.md
cmd/rqlited/main.go

It seems Hashicorp Raft only works in IP addresses, and joining with a hostname caused the remove logic to cause all nodes to leave when one node was instructed to leave.

Used resolved address when joining

---

store/store.go
store/store_test.go

I'm using store as a library in one of my projects, and it's become necessary to introspect the current node's Raft state (currently that's only available by the ``Leader()`` method which requires string matching).
This PR adds an ``IsLeader()`` bool method as well as a ``State()`` method (wrapper around ``raft.State()``).
Tests pass. Let me know if there are any issues/modification you would like to see.

Store methods to expose node Raft state

---

CHANGELOG.md
cmd/rqlited/main.go
db/db.go
db/db_test.go
store/store.go

This was possible previously, but would need to be set every time on startup via the API. This change allows it to set at startup AND enables foreign constraint checking by default.

Support controlling FK constraints at startup

---

cmd/rqlited/main.go
http/service.go
store/store.go
system_test/helpers.go

With this change, if a node receives a join request,, and the receiving node is not the master, it will redirect the requesting node to the master. This allows new nodes to join the cluster through any existing node.

join endpoint returns HTTP 301 if necessary

---

cmd/rqlited/main.go
store/store.go
store/store_test.go
system_test/helpers.go

This is useful in case the server needs to store other metadata (e.g. auth
data) along side the peer list.
The logging bit is handy in case something has its own logging framework
that it wants to use.
Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>

add an API for using custom raft.PeerStore/log.Logger

---

cmd/rqlited/main.go
disco/client.go
disco/client_test.go

This testing has shown that the Lambda function should just return the registered addresses when an attempt is made to register an address already in use.

Start fixing Discovery Redirects

---

cluster/join.go
disco/client.go

Without this, rqlite would behave differently when compiled by Go 1.7 and earlier.
See the Go 1.8 release notes,

Explicitly don't follow redirects

---

CHANGELOG.md
cmd/rqlited/main.go
store/peers.go
store/peers_test.go

The main rqlite code needs this logic to check if the Discovery Service
should even be accessed. This code makes assumptions about how the Raft
module works, which is subject to change. The new unit tests should
capture that.

Don't do any join operations if not required

---

CHANGELOG.md
cmd/rqlite/main.go

HTTP client behavior changed with Go 1.8. This change makes behavior that was implicit in Go 1.7 and earlier, explicit now.

CLI should handle HTTP redirect explicitly

---

doc/DATA_API.md
http/service.go
http/service_test.go

With this change, any URL set as `Location` in the HTTP headers includes the full request path *including* the query params.

Include any query params with 301 redirect URL

---

appveyor.yml

On successful builds, this will package the rqlite binaries and host them using AppVeyor's artifact CDN.
After builds, this will become the permalink to the latest windows build from `master`:
```text
https://ci.appveyor.com/api/projects/rqlite/rqlite/artifacts/rqlited-nightly-win64.zip?branch=master
```
The branch selection ensures that users can't download potentially broken PR builds.

Fix #360, AppVeyor publishes artifacts

---

CHANGELOG.md
cmd/rqlite/main.go

The CLI doesn't yet support passing authentication credentials, but this change means the user will know what is happening.

CLI checks for HTTP 401

---

http/service.go
http/service_test.go
store/store.go
store/store_test.go

The Query() and Execute() functions on the Store now take a complex type that encapsulates the statements, and associated parameters. This will make it easier to add more control parameters when making requests.

New QueryRequest and ExecuteRequest types

---

auth/credential_store.go
auth/credential_store_test.go

`bcryptpass` cmdline informs the credentialStore that received passwords
should be hashed before comparing to the passwords obtained form the
authfile.
Closes #395

auth: Added cmdline option to specify passwords are bcrypted

---

db/db.go

there could be errors during backup in which case the file handle is left
open. Also there could be errors in closing file, catch and return that
too unless there have been prior errors.
Both the cases now stand handled.
Closes #400

Make sure file is correctly closed and catch closing error

---

cmd/rqlite/README.md
cmd/rqlite/main.go

Currently the CLI doesn’t support Basic Auth credentials. This change adds a new option, `-u, —user` to accept an username and password in the form of `username:password`. Credentials are then used to set the Authorization header for all HTTP requests.
Resolves: #369

Add Basic Auth credentials support to the CLI

---

cmd/rqlite/execute.go
cmd/rqlite/main.go
cmd/rqlite/query.go

Currently the CLI doesn’t display the statement timings after executing an SQL query. This change adds a new `.timer on|off` command to enable/disable this feature. When enabled, the CLI will append the `timings` URL query parameter to all query/execute requests sent to the API. When a response is received, the execution time is shown below the result.
Resolves: #317

Add statement timings support to CLI

---

cmd/rqlite/execute.go

Bug introduced in https://github.com/rqlite/rqlite/pull/414.

Correct execute URL in CLI

---

cmd/rqlite/backup.go
cmd/rqlite/execute.go
cmd/rqlite/main.go
cmd/rqlite/query.go

Add a CLI command to call the HTTP API and save the backup file. The API responds with the raw file,
so it cannot be unmarshalled into a struct.
Make sendResponse returns the raw response body and provide a function to parse the raw response
into a struct.
Closes #432

Add Backup method to the CLI

---

http/service.go
http/service_test.go
store/store.go
store/store_test.go

returned data could be of any size and would take up additional space in
ram, instead write the data directly to the passed writer, which in this
case would be http.ResponseWriter
Later this writer could be gzipped buffer writer
There is a wipped commit, as I wanted some input on how to test the backedup file.  I tested manually and it was fine.
I would have to use the db package. But not sure if is a good idea

 write backup directly to ResponseWriter instead of returning

---

cmd/rqlite/main.go

Currently, we initiate a new terminal every iteration by calling the wrapper to the `prompt.NewTerminal()` using `prompt.Basic()` but by creating a separate terminal instance using `prompt.NewTerminal()` we can reduce the multiple instances of terminal getting spawned and also use the history slice implemented by the library by pressing the up/down arrow key.

Enable history for rqlite client

---

cluster/join.go
cluster/join_test.go
cmd/rqlited/main.go
http/service.go
tcp/transport.go
tcp/transport_test.go

The -http-ca-cert and -node-ca-cert options allow the user to specify
trusted X.509 root CA certificates as an alternative to the
-http-no-verify and -node-no-verify options. This behavior is analogous
to the rqlite client -ca-cert option from https://github.com/rqlite/rqlite/pull/550.
A [backport to v4 series is available](https://github.com/zmedico/rqlite/compare/4.3.0-patch...zmedico:server-ca-cert-option-4.3.0).

Server -http-ca-cert and -node-ca-cert options

---

CHANGELOG.md
cluster/service.go
cluster/service_test.go
http/service.go
http/service_test.go
store/store.go
store/store_test.go

With the advent of Raft IDs, this distinction matters.

Add method to Store that returns leader ID

---

CHANGELOG.md
cmd/rqlited/main.go

This will make it easier for client libraries to check for features in a given server, in a standard way.

Add features list to status output

---

cmd/rqlite/execute.go
cmd/rqlite/main.go
cmd/rqlite/query.go

This results in significant duplicated code, but is easier to follow. The previous code was buggy when it came to redirection handling. Longer term tool needs to be rebuilt to use a proper Go SQL-compliant package (yet to be written).

Simplify rqlite implementation

---

CHANGELOG.md
DOC/CLUSTER_MGMT.md
README.md
cluster/join.go
cluster/join_test.go
cmd/rqlited/main.go
http/service.go
http/service_test.go
store/store.go
store/store_test.go
system_test/full_system_test.py

A non-voting node doesn't participate in Raft consensus, but does subscribe to the committed log entries originating with the leader. This means a non-voting node keeps up-to-date with the state machine, without impacting write-latency. These non-voting nodes can provide read scalability for the cluster.

Add support for non-voting nodes

---

DOC/CONSISTENCY.md
http/service.go
store/store.go
store/store_test.go
system_test/cluster_test.go
system_test/helpers.go

This change allows the read request to specify the maximum time the node receiving the request may have last heard from the cluster leader. It only applies to a read consistency selection of None.

 Support leader freshness with None consistency 

---

CHANGELOG.md
cmd/rqlited/main.go
store/store.go

Allow log level control for Raft module

---

DOC/CONSISTENCY.md

Signed-off-by: luo.runbing <luo.runbing@zte.com.cn>

doc: fix typo s/freshess/freshness/

---

cmd/rqlited/main.go
store/store.go

Snapshotting was *never* functional due to the zero interval value.

Set Snapshot Interval to non-zero value

---

cmd/rqlited/main.go
http/service.go
http/service_test.go
system_test/cluster_test.go

This change adds the API protocol uses by each node to the node meta. This new information is then used by non-leader nodes when forming the value returned in the Location header of a HTTP response.

Set Location for HTTP redirect properly for secure nodes

---

cluster/join.go

It's not clear why this code was put in place in the first place, but it may not be necessary.

Do not use resolved address in join request

---

CHANGELOG.md
go.mod
go.sum
http/service.go
http/service_test.go

As per https://blog.cloudflare.com/exposing-go-on-the-internet/
HTTP/2 is enabled automatically on any Go 1.6+ server if:
- the request is served over TLS/HTTPS
- Server.TLSNextProto is nil (setting it to an empty map is how you disable HTTP/2)
- Server.TLSConfig is set and ListenAndServeTLS is used or
- Serve is used and tls.Config.NextProtos includes "h2" (like `[]string{"h2", "http/1.1"}`, since Serve is called too late to auto-modify the TLS Config)

Enable http/2.0 support for TLS

---

CONTRIBUTING.md
db/db.go
db/db_test.go
go.mod
go.sum
store/store.go

This will save a disk read and write (the size of the entire SQLite database) during a database snapshot operation.

Don't use temp file when snapshotting database

---

db/db.go
store/store.go

Previous locking didn't look quite correct, and with the advent of the Serialize() functionality, it needs to be more precise.

Tigthen up Store-level locking

---

db/db.go
db/db_test.go
store/store.go
store/store_test.go
system_test/misc/test-pr739.sh

Saves a read and write, the size of the SQLite database, when restoring an in-memory database.

Don't use temp file when restoring to in-memory SQLite

---

command/marshal.go
system_test/helpers.go
system_test/single_node_test.go

The GZIP writer was being shared -- incorrectly -- by multiple HTTP requests (both queries and executes). But it's not thread safe. Bad, bad, bad.
https://github.com/rqlite/rqlite/issues/781

Create GZIP writer for every compression request

---

cmd/rqlited/main.go
system_test/helpers.go
tcp/transport.go
tcp/transport_test.go

This was clearly a mistake due to a previous code change.

Add CA cert support which was erroneously removed

---

http/service.go
system_test/full_system_test.py

Getting the redirect information requires accessing other nodes, which could block if those nodes are not up.

Remove 'redirect' from HTTP status

---

CHANGELOG.md
cmd/rqlited/main.go
db/db.go
db/db_test.go
store/db_config.go
store/store.go
store/store_test.go
system_test/helpers.go

This is a breaking change. However this feature hasn't been tested and allows end-users to break the system too easily. Low-level control over the SQLite database is better done with PRAGMA commands where possible.

Remove support for specifying SQLite DSN

---

db/db.go
db/db_test.go
store/store.go
system_test/single_node_test.go

Implement the design proposal from @rittneje in https://github.com/mattn/go-sqlite3/issues/959#issuecomment-890371852
This provides correct, true concurrent reads of an in-memory database.

Support true concurrent queries via vfs=memdb

---

store/store.go

Don't wait until Raft layer returns it. There is a small chance of a false leadership detection, but the cluster would have to be in flux anyway for that to be the case. Execute does this already.

Perform leader check first for STRONG query

---

CHANGELOG.md
cluster/client.go
cluster/service_mux_test.go
cluster/service_test.go
http/service.go
http/service_test.go

Deal with intermittent timeout errors during performance measurement on public clouds.
This should be user-configurable in a future release to address https://github.com/rqlite/rqlite/issues/801.

Set timeout when fetching node API address

---

CHANGELOG.md
README.md
db/db_test.go
db/testdata/text.go
go.mod
go.sum
store/store_test.go

Support in-memory databases up to 2GiB in size. See https://sqlite.org/forum/forumpost/b1ba232667130afa?t=h.

Upgrade dependencies, rqlite/go-sqlite3 1.22.0

---

CHANGELOG.md
db/db.go
db/db_test.go
store/store.go

This is safe according to https://sqlite.org/howtocorrupt.html and avoids any sqlite3_serialize() limitations.

Serialize on-disk databases by simply reading SQLite file

---

CHANGELOG.md
cmd/rqlited/main.go
system_test/full_system_test.py

There is no point waiting for join operations to complete before starting the HTTP server. In the event the join fails it just introduces delays due to join-retrys. The HTTP API service is meant to be robust in the face of a non-ready underlying Store anyway.

Start the HTTP server before doing any joins

---

CHANGELOG.md
DOC/CLUSTER_MGMT.md
appveyor.yml
db/db.go
store/store.go
store/store_test.go
system_test/cluster_test.go
system_test/helpers.go
system_test/single_node_test.go

Adds support to recover failed clusters, or clusters that restart with all new Raft network addresses.
Borrows heavily from the Consul approach.

Support recovering clusters that have permanently lost quorum

---

cmd/rqlite/main.go

During the execution of SQL through the console, the result of numeric type will be deserialized to float64 and displayed as scientific notation

fix:solve the float64 problem during JSON deserialization

---

db/db_test.go

Let's see if this helps these tests run faster, especially with -race, and prevent CircleCI timeouts.

Don't run heavy memory tests in parallel

---

.circleci/config.yml
CHANGELOG.md
system_test/full_system_test.py

`sed` was super useful for this work.
```bash
sed 's/self\.assertEqual(str(j), "\(.\+\)")/self\.assertEqual(j, d_("\1"))/'`
```
was run across the file.

Migrate end-to-end testing to Python3

---

DOC/SECURITY.md
auth/credential_store.go
auth/credential_store_test.go
cluster/join.go
cluster/join_test.go
cmd/rqlited/main.go
http/service.go
http/service_test.go
system_test/full_system_test.py

This change enhances the authentication and authorization system in two ways.
- Adds a new command-line option, `-join-as` which tells rqlite to read the username and password from the auth config file, when doing the join. This allows us to avoid putting passwords in the launch command.
- Adds support for a pseudouser in the auth config, indicated by `*`. This allows indicating that all requests -- even anonymous requests -- have any permissions assigned to `*`.

Enhance Authentication and Authorization system

---

http/service.go
http/service_test.go

This shouldn't happen, but it might, this will allow the underlying error to be returned to the caller. The body of the response will now look something like:
{
"results": [],
"error": "some error",
"time": 0.021976516
}

Return a clearer response if no DB results

---

CHANGELOG.md
cmd/rqlited/flags.go
cmd/rqlited/main.go
log/log.go
log/log_test.go
store/store.go

When true, skips syncing freelist to disk. This improves the database write performance under normal operation, but requires a full database re-sync during recovery.# Please enter the commit message for your changes.

Control whether bbolt syncs freelist to disk

---

CHANGELOG.md
command/encoding/json.go
command/encoding/json_test.go
db/db_test.go
system_test/full_system_test.py

JSON output from rqlite is not meant for raw display on web pages, so no need to escape. Escaping would also interfere with some characters output by SQLite.

Don't HTML escape JSON output

---

CHANGELOG.md
DOC/CONSISTENCY.md
store/store.go
store/store_test.go

It doesn't make sense to check the last leader-contact time when the node itself is the leader. Any read, when served by the leader, is going to be within the freshness bound.
Fixes https://github.com/rqlite/rqlite/issues/1048

Ignore freshness when serving queries on Leader

---

auth/credential_store.go
http/service.go

Makes it cleaner to re-use them outside of HTTP package.

Move Perm constants to auth package

---

queue/queue_test.go
store/store_test.go

https://pkg.go.dev/testing#T.Fatalf
> Fatalf is equivalent to Logf followed by FailNow.
https://pkg.go.dev/testing#T.FailNow
> FailNow marks the function as having failed and stops its execution by calling runtime.Goexit (which then runs all deferred calls in the current goroutine).

fix minor unreachable code caused by t.Fatal

---

DOC/SECURITY.md

There is a typo in the security documentation. The flag `-no-node-verify` is misspelled and should be corrected to `-node-no-verify`.
See
```
cmd/rqlited/flags.go:	flag.BoolVar(&config.NoNodeVerify, "node-no-verify", false, "Skip verification of a remote node cert")
```

fixed typo: flag is -node-no-verify, not -no-node-verify

---

CHANGELOG.md
cluster/bootstrap.go
http/service.go
http/service_test.go
store/store.go

If a non-resolvable address is passed to the Store, and then Store then adds that to the config, it can result in a cluster that seems to have insufficient members (since the remote node can't be contacted). This may trigger a new leader election.

Notified node checks address resolution

---

go.mod
go.sum

```bash
bin/rqlited (gobinary)
Total: 2 (HIGH: 2, CRITICAL: 0)
┌───────────────────┬────────────────┬──────────┬────────────────────────────────────┬───────────────────────────────────┬─────────────────────────────────────────────────────────────┐
│      Library      │ Vulnerability  │ Severity │         Installed Version          │           Fixed Version           │                            Title                            │
├───────────────────┼────────────────┼──────────┼────────────────────────────────────┼───────────────────────────────────┼─────────────────────────────────────────────────────────────┤
│ golang.org/x/net  │ CVE-2022-27664 │ HIGH     │ v0.0.0-20220826154423-83b083e8dc8b │ 0.0.0-20220906165146-f3363e06e74c │ golang: net/http: handle server errors after sending …
```

Update packages to resolve CVE-2022-32149 and CVE-2022-27664

---

system_test/cluster_test.go

This is not great, but extensive testing on Windows has not been successful yet, so skip this test for now.
https://github.com/rqlite/rqlite/issues/1123

Skip Test_MultiNodeClusterLargeQueuedWrites on Windows

---

CHANGELOG.md
cluster/client.go
cluster/service.go

Cluster-client operations may fail if the remote node has restarted, leaving the connection pool's connections in stale state. This change has the client retry repeatedly with a new connection, which should force a new, valid, connection to be made with the restarted remote node.

Retry certain cluster-client operations

---

CHANGELOG.md
cluster/bootstrap.go
cluster/bootstrap_test.go
cmd/rqlited/main.go
system_test/e2e/auto_clustering.py

Probably the fix for https://github.com/rqlite/rqlite/issues/1290
This logic was always too conservative, bootstrapping will do a join first, which is fine.

Bootstrap and join if requested

---

CHANGELOG.md
db/db.go
store/store.go

The SQLite docs state that this risks database corruption in the event of a crash, but that's OK, as rqlite always blows away the database on startup and rebuilds it from the Raft log.
In my testing this results in 3x speed-up in write performance -- you get 3x the INSERT rate.

Set 'synchronous' to OFF for on-disk databases

---

CHANGELOG.md
db/db.go
db/db_common_test.go
db/db_inmem_test.go
db/db_ondisk_test.go
db/db_test.go
store/store.go

If the Store creates an on-disk database, it still enables DELETE mode.

Add full WAL-support to DB layer

---

CHANGELOG.md
log/log.go
log/log_test.go
store/store.go

This ensures the system doesn't apply uncommitted log entries to the FSM, if it runs the in-memory startup. There have been no reports of this in the field -- it is an edge case -- but this removes any chance of it.

Periodically record actual applied index

---

CHANGELOG.md
cmd/rqlited/flags.go
cmd/rqlited/main.go
store/store.go
store/store_restart_test.go

With the move to WAL and "synchronous mode" to OFF, on-disk startup times are very close to in-memory. There is no need for this control anymore and it complicates the start-up code.

Remove on-disk-startup control

---

system_test/helpers.go

CI systems might be a bit slower.

Increase election timeout during testing

---

CHANGELOG.md
db/db.go

Connections where coming from the pool, and if they were new, they had autocheckpointing set back to 1000!

1 RW DB connection only!

---

cmd/rqlite/main.go

When using the `rqlite` CLI, I could not determine an issue of connection. It turns out that the arguments I had provided were not working. The issue was not present until I added a timeout to the HTTP client.

provide a default timeout on http client

---

scripts/release_creator.py

There is a missing dash that causes the `cd` command to fail, if one is following/automating the instructions blindly.

release: add missing dash in linux quickstart instructions

---

cmd/rqlited/flags.go
cmd/rqlited/main.go
http/service.go
http/service_test.go

This PR fixes #687, closes #1168, and closes #1175.
This PR implements the solution decided on in #1168 by allowing user control of `Access-Control-Allow-Origin` and setting `Access-Control-Allow-Methods`, `Access-Control-Allow-Headers`, and `Access-Control-Allow-Credentials` to values that allow CORS compatible access to rqlite. Additionally, it handles `OPTIONS` requests to allow for CORS preflight requests to work. These steps enable rqlite servers to be accessed through HTTP requests in browsers.

Support accessing rqlite in browsers by setting appropriate Access-Control-Allow headers and handling OPTIONS requests

---

db/db_common_test.go

String compare may be brittle. See: https://ci.appveyor.com/project/otoolep/rqlite/builds/48587534

Test Dump by reloading it into new database

---

CHANGELOG.md
http/nodes.go
http/nodes_test.go
http/service.go
system_test/cluster_test.go
system_test/e2e/helpers.py
system_test/helpers.go
system_test/single_node_test.go

Make the JSON response construction cleaner. This output format can be enabled by pass `ver=2` to the URL.

Improve nodes/ JSON response

---

CHANGELOG.md
db/db.go
db/wal/compacting_scanner.go
db/wal/compacting_scanner_test.go
db/wal/full_scanner.go
db/wal/reader.go
db/wal/writer_test.go
store/store.go

This halves the Compacting Scan time, and doesn't seem necessary since rqlite is the only system writing the WAL files.

Support skipping verifying frame data

---

CHANGELOG.md
cmd/rqlited/flags.go

This can now go lower, since Raft snapshotting is more efficient. The upside is that few logs will need be replayed when a node restarts, which will result in shorter startup times. We may be able to go even lower -- Consul defaults to 1024.
The downside is more Snapshotting, which pauses the system during that time. But the pause times should be very short.

Reduce Raft threshold to 2048

---

CHANGELOG.md
snapshot/sink_test.go
snapshot/store.go
snapshot/store_test.go
store/store.go

It may be necessary to override the FullNeeded definition, so wrap it.

Add FullNeeded() to Snapshot store

---

CHANGELOG.md
auto/backup/uploader.go
auto/backup/uploader_test.go
cmd/rqlited/main.go

Possible fix for https://app.circleci.com/pipelines/github/rqlite/rqlite/3648/workflows/d1235267-093d-4ac7-8d8d-061bc2ac9744/jobs/26157
The idea is be sure one test's goroutines are fully closed before starting the next test.

Move uploader goroutine into Uploader

---

CHANGELOG.md
cmd/rqlite/main.go

If UserHomeDir() doesn't have a value, this can happen. Fixes https://github.com/rqlite/rqlite/issues/1486. May also be caused by failure to open the history file. In any event, this is not something that should block the CLI from working.

Guard against nil History

---

CHANGELOG.md
auth/credential_store.go
auth/credential_store_bench_test.go
auth/credential_store_test.go

See https://github.com/rqlite/rqlite/issues/1488
bcrypt support wasn't adding any extra security, and had the potential of making end users think they were more secure than they were.

Remove faulty bcrypt support

---

system_test/helpers.go

The HTTP service depends on the Store, not the other way around. This should address https://app.circleci.com/pipelines/github/rqlite/rqlite/3793/workflows/f87affa5-3671-498a-afba-f0ef104a9a0c/jobs/28530

Shutdown the HTTP service first during testing

---

CHANGELOG.md
cmd/rqlited/flags.go

It's been obsolete and ignored since 8.0 was released, because nodes now join using the Raft port.

Remove obsolete http-no-verify command-line flag

---

CHANGELOG.md
cmd/rqlited/main.go

If these had been typed, would have all been good.
https://github.com/rqlite/rqlite/issues/1507

Fix order of variables passed to rtls

---

CHANGELOG.md
cmd/rqlited/flags.go

With Raft snapping also triggerable by WAL size, I think it makes more sense to check for the 16MB (default) WAL size more regularly.

Reduce Raft snap check time to 10 seconds

---

cmd/rqlited/flags.go

Bring this into line with standard SQLite WAL checkpoint threshold. See https://www.sqlite.org/wal.html
"By default, SQLite does a checkpoint automatically when the WAL file reaches a threshold size of 1000 pages." Default page size in 4KB.

Make the default WAL snap threshold 4MB

---

CHANGELOG.md
store/store.go
store/store_test.go

Add a unit test too, checking if WAL-triggered snapshotting actually happens.

Cleaner WAL goroutine handling

---

auto/backup/uploader.go
auto/restore/downloader.go
aws/s3.go
aws/s3_test.go
cmd/rqlited/main.go

AWS has deprecated path-style URLs but it's required for some S3-like alternatives such as Minio.
This is a PR for #1560, which allows the user to force the S3 path style to work with Minio.  Marked as draft as updates to tests are still needed.
I will pair it with a docs PR against [rqlite/rqlite.io](https://github.com/rqlite/rqlite.io) later tonight, to show examples of how to configure rqlite with Wasabi (which it turns out doesn't need forced path style) and Minio (which does).

Allow configurable S3 path style for auto backups

---

CHANGELOG.md
auto/backup/uploader.go
auto/backup/uploader_test.go
cmd/rqlited/main.go
db/db.go
db/db_test.go
store/provider.go
store/provider_test.go
store/store.go
system_test/e2e/auto_state.py
system_test/e2e/helpers.py

The docs always stated that the upload only ran on the Leader, but this wasn't the actual case.

Improve auto-backup efficiency and only run on Leader

---

CHANGELOG.md
snapshot/store.go
snapshot/store_test.go

If rqlite was killed after snapshot-creation, but before reaping took place, Snapshot List() would return the oldest snapshot, not the newest. This is not compliant with Hashicorp Raft requirements.

List the newest snapshot, not oldest

---

CHANGELOG.md
db/db.go
db/state_test.go

Add extensive testing of the interaction between VACUUM, WAL checkpoint, and WAL copying.
https://github.com/rqlite/rqlite/issues/1609

Add more involved WAL checkpoint unit test

---

auto/restore/downloader.go
aws/s3.go
aws/s3_test.go
cmd/rqlited/main.go

The AWS session and s3 manager are concurrent safe, they should be reused whenever possible:
Sessions are safe to use concurrently as long as the Session is not
being modified. Sessions should be cached when possible, because
creating a new Session will load all configuration values from the
environment, and config files each time the Session is created.
See https://pkg.go.dev/github.com/aws/aws-sdk-go/aws/session
Currently, an aws session and s3 client/manager are created every time a call to Upload, CurrentID or Download is made. I changed it so it creates one session and S3 manager during app startup and reuse it afterwards.

aws: reuse session and S3 manager

---

CHANGELOG.md
random/random.go
random/random_test.go
store/store.go

We don't want every node in the cluster to perform a WAL size snapshot at the same time.

Jitter the WAL size check interval

---

store/store.go

Load testing shows this results in shorter snapshot times.

Use defer only to make sure WAL file is closed

---

CHANGELOG.md
cluster/client.go
cluster/service.go
tcp/pool/channel.go
tcp/pool/channel_test.go

This couples dialing between nodes, and if one is unreachable, it can slow down connecting to other nodes for any reason, such as queries.

Don't attempt to dial nodes while holding onto Pools lock

---

cmd/rqlited/main.go

Ensure the Store can't be modified during its shutdown process.

Shutdown all network resources before Store

---

CHANGELOG.md
db/db.go
db/db_test.go
db/state.go
db/state_test.go

This sets us up for any future Extensions or Connect Hooks support.

Move to "named" registration of the SQLite3 driver

---

.circleci/config.yml
CHANGELOG.md

This ensures that end-to-end test binaries are built in the same way as the actual release binaries.

Align CircleCI and release-build flag

---

CHANGELOG.md
db/db_test.go
db/driver.go
db/driver_test.go
db/state.go
db/state_test.go
snapshot/sink.go
snapshot/store.go
snapshot/upgrader.go
store/store.go

As part of the 9.0 design, rqlite must not checkpoint any database when it's closed, as that would put the primary SQLite database in an invalid state -- WAL files would be checkpointed even though a Snapshot had not occurred. This gets this change into master, reducing the changes that will arrive due to other 9.0 changes.

No checkpoint on close

---

CHANGELOG.md
store/store.go
store/store_test.go

This is important to ensure meaningful node-restart testing.

Reset Store state on open

---

CHANGELOG.md
store/fsm.go
store/fsm_test.go
store/store.go
store/store_multi_test.go

This addresses a highly unlikely, but possible failure case, which could result in an inconsistent cluster or data loss.
This requires a snapshot to be triggered just after a node joins a cluster. This is highly unlikely in practise because cluster membership changes usually take place at a very low rate, and snapshotting also (usually) takes place at a very low rate. For this to have a realistic chance to happen would require both a high rate of cluster-membership changes and a high rate of writes.
This issue has never been reported in production.

Full snapshot needed if Snapshot-Persist is not called (or fails)

---

CHANGELOG.md
rsync/ready_channels.go
rsync/ready_channels_test.go
store/store.go

This will allow this primitive to be more widely used.

Factor out ReadyChans

---

CHANGELOG.md
store/store.go

This mutex has not been needed since rqlite moved to WAL-based snapshotting.

Remove Query Transaction mutex

---

CHANGELOG.md
store/store.go

The Term could be updated by log entries that are never passed to the FSM layer.

Read Term from Raft level

---

CHANGELOG.md
store/store.go

Otherwise we can't tell the difference between a Strong Read being applied due to reapplication of logs due to start-up or an actual query since start-up.

Record term of Strong Read at actual query time

---

db/db.go

Avoid unneeded allocations in for cycle

Reduce memory allocations in queryStmtWithConn

---

command/chunking/chunk_dechunk_test.go
command/chunking/dechunker_test.go
db/db_test.go
db/state_test.go
rarchive/targz_test.go
rarchive/zip_test.go

The PR refactors tests that contain `os.MkdirTemp` with [`T.TempDir`](https://pkg.go.dev/testing#T.TempDir):
> TempDir returns a temporary directory for the test to use. The directory is automatically removed when the test and all its subtests complete.
This PR removes 60 lines of test code without harming readability.
---
*I came to the repo after reading [this article](https://philipotoole.com/how-is-rqlite-tested/)*.

Simplify tests by using t.TempDir instead of os.MkdirTemp

---

cmd/rqlite/main.go
cmd/rqlited/flags.toml

The PR corrects grammar issues in help strings for `rqlite` and `rqlited`.

Fix typos in help strings

---

auto/backup/config_test.go
auto/restore/config_test.go

The PR refactors tests by changing to use https://pkg.go.dev/testing#T.Setenv instead of `os.Setenv`:
> Setenv calls os.Setenv(key, value) and uses Cleanup to restore the environment variable to its original value after the test.

Simplify tests by using t.Setenv instead of os.Setenv

---

command/sql/processor.go
command/sql/processor_bench_test.go
db/db_common_test.go
random/random.go
random/random_test.go
tcp/pool/channel_test.go

This PR refactors code to use [`math/rand/v2`](https://go.dev/blog/randv2) instead of [`math/rand`](https://pkg.go.dev/math/rand).
Changes:
- Replace all imports `math/rand` with `math/rand/v2`.
- Simplify the `random` package implementation by removing the now unnecessary mutex and seed. See [this explanation](https://go.dev/blog/randv2#:~:text=Having%20eliminated%20repeatability,Go%201%20generator).
- Add `random.StringN`. Use it inside the `random.String` implementation and instead of `generateRandomString`.
- Replace `random.Intn` with `rand.N`.
- Remove unused `random.Float64`. It can be replaced with `rand.Float64`.
- Replace `time.Sleep(time.Millisecond * time.Duration(random.Intn(100)))` with `time.Sleep(rand.N(100 * time.Millisecond))` as the blog post …

Simplify random package with math/rand/v2

---

cdc/fifo.go

Collect and delete keys that are less than or equal to the requested index. 
Removing key/values pairs in a bucket during iteration on the bucket using cursor may not work properly. Each time when removing a key/value pair, the cursor may automatically move to the next position if present. When users call c.Next() after removing a key, it may skip one key/value pair. Refer to etcd-io/bbolt#611 for more detailed info.

Implement key collection and deletion in FIFO
