rqlite/rqlite

- README.md
- server/server.go
- server/single_server_test.go
> Change API for ease of use

- command/execute_command.go
- db/db.go
- interfaces/interfaces.go
- log/log.go
- log/log_test.go
- main.go
- server/server.go
- server/single_server_test.go
- server/statemachine.go
With #25 a bug was introduced, so rqlite raised a panic whenever
starting because data path wasn't correctly created.
This commit attempts to fix this bug, and so #25 changes can be
finally applied.
> Fix data path creation and merge #25 again

- db/db.go
- http/service.go
- store/store.go
Backup endpoint also added, but not fully-functional.
> Move to POST for bulk queries

- db/db.go
- db/db_test.go
Merge this only after https://github.com/mattn/go-sqlite3/pull/282 has been merged.
> Use SQLiteRows.DeclTypes() to fix issue #52

- CHANGELOG.md
- SECURITY.md
- cmd/rqlited/main.go
- http/credential_store.go
- http/credential_store_test.go
- http/service.go
Fixes https://github.com/otoolep/rqlite/issues/83
> Basic auth support

- CHANGELOG.md
- cmd/rqlited/main.go
- db/db.go
- db/db_test.go
- store/store.go
- store/store_test.go
- system_test/helpers.go
> Support restore to in-memory databases

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- cmd/rqlited/main.go
- http/service.go
- http/service_test.go
- package.sh
- store/store.go
- system_test/helpers.go
- vagrant_setup.sh
> Move to new rqlite org

- CHANGELOG.md
- README.md
- cmd/rqlited/main.go
With low-latency networks, this results in a noticeable performance increase.
> Switch to in-mem database by default

- CHANGELOG.md
- cmd/rqlited/main.go
- tcp/mux.go
- tcp/mux_test.go
Fixes https://github.com/rqlite/rqlite/issues/79
> Allow Raft address advertise

- .gitignore
- cmd/rqlite/README.md
- cmd/rqlite/execute.go
- cmd/rqlite/main.go
- cmd/rqlite/query.go
Options of `rqlite-cli`
```sh
Options:
-h, --help
display help
-s, --scheme[=http]
protocol scheme(http or https)
-H, --host[=127.0.0.1]
rqlited host address
-p, --port[=4001]
rqlited listening http(s) port
```
Screenshot
> impl rqlite-cli

- cmd/rqlite/README.md
This follows the pattern of MySQL.
> Just call the rqlite CLI 'rqlite'

- db/db.go
@otoolep Fixes #130. Tests pass.
Turns out that json.Marshal will base64-encode any []byte values it finds by default, so no changes to the http service are necessary. It's still an open question why go-sqlite is returning ``[]byte`` values for text columns.
> db: only convert row value to string if the column type is text

- CHANGELOG.md
- http/service.go
- http/service_test.go
- store/store.go
- store/store_test.go
Support removing a node from the cluster.
Fixes https://github.com/rqlite/rqlite/issues/105
> Add remove node

- CHANGELOG.md
- http/service.go
- http/service_test.go
Also corrects production code, that was expecting incorrect HTTP method.
> More Service route unit tests

- system_test/single_node_test.go
These tests check some error-handling situations.
> More single-node system tests

- CHANGELOG.md
- cmd/rqlite/main.go
Fixes https://github.com/rqlite/rqlite/issues/123
> CLI follows 301 redirect

- CHANGELOG.md
- http/service.go
- http/service_test.go
Fixes https://github.com/rqlite/rqlite/issues/158
> Add rqlite version to each HTTP response

- CONTRIBUTING.md
Fixes https://github.com/rqlite/rqlite/issues/161
> Always fetch latest SQLite support

- http/service.go
- store/store.go
Bump the batch size to 1000 too.
> Use a transaction for loaded batch

- cmd/rqlite/execute.go
- cmd/rqlite/main.go
- cmd/rqlite/query.go
Hi,
I've been playing around with embedding rqlite into another application. Here's some patches that I found useful while experimenting.
> Add rqlite flexibility

- store/store.go
Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>
> store: use ErrNotLeader everywhere

- store/store.go
Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>
> expose raft's observer API via store

- db/db.go
- db/db_test.go
This is the start of a code change to handle this comprehensively.
> Start handling the various SQLite TEXT types

- store/store.go
This allows us to grab a raw snapshot of the databse.
Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>
> add a raw snapshotting API

- CHANGELOG.md
- cmd/rqlited/main.go
- http/service.go
- http/service_test.go
- system_test/single_node_test.go
Common Table Expressions can begin with WITH. This check was always dubious.
> Not all queries begin with SELECT so pull check

- CHANGELOG.md
- cmd/rqlited/main.go
- doc/SECURITY.md
- system_test/end_to_end_enc.sh
- tcp/mux.go
- tcp/mux_test.go
- testdata/x509/resources.go
https://github.com/rqlite/rqlite/issues/93
> TLS-encrypted node-to-node encryption

- CHANGELOG.md
- cmd/rqlited/main.go
Strictly speaking the system is rqlite, not rqlited. The latter is just the daemon.
> Tweak start-up logo

- CHANGELOG.md
- cmd/rqlited/main.go
- http/service.go
- http/service_test.go
- tcp/mux.go
Mux is first service to register status for serving.
> HTTP service now supports registered statuses

- testdata/x509/scripts/prep-certs.sh
From https://jamielinux.com/docs/openssl-certificate-authority/introduction.html
> Add cert-generation helper script

- http/service.go
- http/service_test.go
Addresses https://github.com/rqlite/rqlite/issues/333
> Don't always set Content-Type as JSON

- cmd/rqlited/main.go
This will make it easier for other services to use the credential store.
> Refactor credential store instantiation

- CHANGELOG.md
- http/service.go
- store/store.go
Fixes issue https://github.com/rqlite/rqlite/issues/391
> Return redirect if node removal executed on follower

- CHANGELOG.md
- DOC/SECURITY.md
- auth/credential_store.go
- auth/credential_store_test.go
Follow up to https://github.com/rqlite/rqlite/pull/397
> Tweak hashed password implementation

- circle.yml
- cmd/rqlited/main.go
- store/store.go
- system_test/full_system_test.py
This addresses the race between opening and the store and starting the
join. It's not robust however, and needs more work.
> Do not wait for log application before joining

- DOC/CLUSTER_MGMT.md
- README.md
- cmd/rqlited/main.go
> Use Raft network address as node ID, by default

- system_test/full_system_test.py
Address https://github.com/rqlite/rqlite/issues/426 and https://github.com/rqlite/rqlite/issues/428
> Full system address advertisement testing

- system_test/full_system_test.py
Addresses https://github.com/rqlite/rqlite/issues/423
> End-to-end backup-and-restore test

- auth/credential_store_test.go
- aws/metadata_test.go
- circle.yml
- cluster/join_test.go
- db/db_test.go
- disco/client_test.go
- http/service_test.go
- store/store_test.go
- system_test/cluster_test.go
- system_test/single_node_test.go
- tcp/transport_test.go
Test run goes from 46 seconds to 16 seconds on my box.
> Parallelize unit tests

- cmd/rqlite/backup.go
- cmd/rqlite/execute.go
- cmd/rqlite/main.go
- cmd/rqlite/query.go
User's current FK constraint configuration is added to the restore file
so the DB preserves the same value
> Create a CLI command to restore the database from a dump file

- CHANGELOG.md
- DOC/BACKUPS.md
- db/db.go
- db/db_test.go
- store/store.go
- store/store_test.go
- system_test/full_system_test.py
This change exposes a more connection-oriented database abstraction to the rest of the system, which should make it easier to implement full transaction support.
> New connection-oriented database layer

- store/connection.go
- store/connection_test.go
- store/store.go
This keeps time transaction-start time on a Connection accurate.
> Add transaction state change checker

- store/connection.go
- store/connection_test.go
- store/store.go
- store/store_test.go
Fix for https://github.com/rqlite/rqlite/issues/473
> Connections now stored in Snapshot

- DOC/DATA_API.md
- http/service.go
- store/command.go
- store/store.go
> Replace use of "transaction" with "atomic"

- http/handlers.go
- http/service.go
- http/service_test.go
Addresses https://github.com/rqlite/rqlite/issues/503
> Support setting connection timings over HTTP

- store/store.go
Fixing a bug that is clearly a typo.
> Don't ignore Join error, return it

- store/store.go
Signed-off-by: runsisi <runsisi@zte.com.cn>
> Fix possible nil pointer dereference

- store/store.go
Signed-off-by: runsisi <runsisi@zte.com.cn>
> Fix missing return in (s *Store) setMetadata

- cmd/rqlite/main.go
The -ca-cert option allows the user to specify a trusted X.509 root CA
certificate as an alternative to the --insecure option.
> Add rqlite -ca-cert option to specify trusted root CA certificate

- cmd/rqlite/backup.go
- cmd/rqlite/main.go
To be able to proxy into a docker network would be handy. I would imagine it wouldn't hurt to have the flexibility in general.
> add proxy support

- CHANGELOG.md
- cmd/rqlite/main.go
> Add support for BasicAuth to CLI

- CHANGELOG.md
- cmd/rqlite/execute.go
- cmd/rqlite/main.go
- cmd/rqlite/query.go
Port of https://github.com/rqlite/rqlite/pull/414
> Support showing timings in the CLI

- CHANGELOG.md
- cmd/rqlite/main.go
> CLI now supports history

- CHANGELOG.md
- db/db.go
- db/db_test.go
- http/service.go
- http/service_test.go
- store/store.go
- store/store_test.go
Port of https://github.com/rqlite/rqlite/pull/448 to v4.6
> Abort transaction if load operation fails

- CHANGELOG.md
- cmd/rqlite/backup.go
- cmd/rqlite/execute.go
- cmd/rqlite/main.go
- cmd/rqlite/query.go
> Add restore command to CLI

- CHANGELOG.md
- db/db.go
- db/db_test.go
> DB layer supports generating SQL format backups

- CHANGELOG.md
- db/db.go
- db/db_test.go
- http/service.go
- http/service_test.go
- store/store.go
> Store layer supports generating SQL format backups

- CHANGELOG.md
- cmd/rqlite/backup.go
- cmd/rqlite/main.go
> Add .dump to CLI

- CHANGELOG.md
- cmd/rqlite/backup.go
- cmd/rqlite/main.go
> Add HTTP proxy (from environment) support

- store/store.go
> Don't ignore Join error, actually return it

- db/db.go
Also catch any error that occurs during close.
> Ensure backup is correctly closed

- CHANGELOG.md
- db/db.go
- db/db_test.go
https://github.com/rqlite/rqlite/pull/494
> JSON types are also text

- CHANGELOG.md
- http/service.go
- http/service_test.go
- store/store.go
- store/store_test.go
This avoids making an extra copy in RAM. Port of original PR #461.
>  Write backup and dump files to a writer 

- DOC/FAQ.md
- store/store_test.go
Branched from https://github.com/rqlite/rqlite/pull/635
> Check level before any freshness check

- DOC/DESIGN.md
- DOC/RESTORE_FROM_SQLITE.md
Great documentation!
While reading it, I encountered a few small typos which are fixed in this PR.
> Fixed spelling in docs

- store/store_test.go
If the snapshot count didn't change, the test didn't actually fail.
> Fix Snapshot test

- http/service.go
- http/service_test.go
- system_test/full_system_test.py
To do this these functions needed to be made public.
> Fix and Test LeaderAPIAddr and LeaderAPIProto

- CHANGELOG.md
- db/db.go
- db/db_test.go
- http/request_parser.go
- http/request_parser_test.go
- http/service.go
- store/command.go
- store/store.go
- store/store_test.go
- system_test/full_system_test.py
- system_test/helpers.go
- system_test/single_node_test.go
Add support as requested in https://github.com/rqlite/rqlite/issues/140
> Support parameterized queries

- system_test/full_system_test.py
> Test snapshotting in a simpler manner

- cmd/rqlite/backup.go
https://github.com/rqlite/rqlite/issues/678
> Set BasicAuth when needed during restore

- cmd/rqlite/backup.go
It can now handle HTTP 301 redirects properly.
> Restore request should re-read file every attempt

- CHANGELOG.md
- cluster/join.go
It doesn't actually address the issue, so let's avoid those types of changes for now.
> Revert resolving Raft addresses

- cmd/rqlited/main.go
> Exit if arguments are passed after data directory

- README.md
If you use OSX instead of macOS in your doc, it suggests that the source does not work on recent versions of macOS.
> Use macOS instead of OSX

- store/store.go
- system_test/full_system_test.py
Don't allow control over trailing logs directly, just implement a policy that scales the number by 1.25 relative to Snapshot threshold. Without doing this it may be that setting the snapshot threshold lower doesn't actually affect SQLite start up times, due to log application. Perhaps this really needs exposure at the command line, but the command line is starting to get complicated.
> Implement policy over trailing Raft logs

- store/store.go
- store/store_test.go
- system_test/helpers.go
- system_test/single_node_test.go
Test cases:
- no snapshots, no commands in log.
- no snapshots, no database commands in log.
- snapshots, no commands in log
- snapshots, commands in log
- snapshots, database commands in log
- snapshots, but no database commands in snapshot
> More testing of snapshot and restore

- store/store.go
Fixes https://github.com/rqlite/rqlite/issues/763
> Convert Raft stats to numbers where possible

- go.mod
- go.sum
This version fixes a memory leak.
> Upgrade to rqlite/go-sqlite3 1.20.1

- cmd/rqlited/main.go
https://github.com/rqlite/rqlite/issues/774
> Tweak help message for source IP

- cluster/join.go
- cluster/join_test.go
- cmd/rqlited/main.go
> Remove metadata from Join operations

- DOC/DIAGNOSTICS.md
- cmd/rqlite/main.go
- http/service.go
- http/service_test.go
- system_test/cluster_test.go
- system_test/full_system_test.py
- system_test/helpers.go
- system_test/single_node_test.go
See doc updates in this PR to understand feature.
> Supporting /nodes endpoint

- system_test/full_system_test.py
Some testing involves changing leaders, and some API checks will be inherently racy.
> Don't always run leader-constraint check

- db/db.go
- store/store.go
Possible, albeit simple, fix for https://github.com/rqlite/rqlite/issues/830
This is going to affect read performance, as concurrent reads can no longer take place. Without more work, this is unavoidable for now.
> Sync use of DB connection

- cmd/rqlited/main.go
- db/db.go
- tcp/mux.go
Fixes https://github.com/rqlite/rqlite/issues/837.
> Don't leak a database if deserialization fails

- CHANGELOG.md
- db/db.go
- db/db_test.go
https://github.com/mattn/go-sqlite3/issues/959#issuecomment-890283264
> Limit in-memory connection pool to 1 connection

- db/db.go
- db/db_test.go
- store/store.go
https://github.com/rqlite/rqlite/issues/843
> Add SQLite compile-time options to status output

- db/db_test.go
- go.mod
- go.sum
Upgrade to v1.21.0, bringing in:
```
-DSQLITE_OMIT_SHARED_CACHE
-DSQLITE_ENABLE_JSON1
-DSQLITE_ENABLE_DBSTAT_VTAB
```
> Upgrade to new compile options

- DOC/PRAGMA.md
- cmd/rqlite/main.go
- cmd/rqlite/query.go
Add a doc about rqlite and PRAGMA.
> CLI supports PRAGMA directives

- cmd/rqlite/main.go
Fixes https://github.com/rqlite/rqlite/issues/854.
> Fix SELECT in CLI

- CHANGELOG.md
- cluster/client.go
- cluster/service.go
- cluster/service_mux_test.go
- cluster/service_test.go
- cmd/rqlited/main.go
- system_test/helpers.go
- tcp/dialer.go
- tcp/dialer_test.go
- tcp/mux.go
- tcp/mux_test.go
This refactoring will make it clearer and simpler to add transparent request forwarding.
> Create dedicated client for talking to a cluster service

- cluster/client.go
- cluster/service.go
- cluster/service_test.go
- cmd/rqlited/main.go
- http/service.go
- http/service_test.go
- system_test/full_system_test.py
- system_test/single_node_test.go
- tcp/pool/LICENSE
- tcp/pool/channel.go
- tcp/pool/channel_test.go
- tcp/pool/conn.go
- tcp/pool/conn_test.go
- tcp/pool/pool.go
Many thanks to https://github.com/fatih/pool.
> Use a connection pool for internode communications

- cluster/client.go
- tcp/pool/channel_test.go
- tcp/pool/conn.go
- tcp/pool/conn_test.go
It's already in the pool package.
> Conn, not PoolConn

- CHANGELOG.md
- DOC/DIAGNOSTICS.md
- DOC/SECURITY.md
- http/service.go
- http/service_test.go
- system_test/full_system_test.py
- system_test/helpers.go
- system_test/single_node_test.go
> Add readyz/ handler

- cmd/rqlite/main.go
Copy fix from https://github.com/rqlite/rqlite/pull/922
> Fix number display for .status

- CHANGELOG.md
- cmd/rqlited/main.go
Fixes https://github.com/rqlite/rqlite/issues/347
> Ignore disco ID if there is preexisting state

- CHANGELOG.md
- cmd/rqlited/main.go
Fixes https://github.com/rqlite/rqlite/issues/713.
> Ignore own join address if passed

- cmd/rqlited/main.go
- store/store.go
- store/store_restart_test.go
- store/store_test.go
https://github.com/rqlite/rqlite/issues/928
> Support disabling in-memory init of on-disk

- CHANGELOG.md
- cluster/join.go
- disco/client.go
- system_test/helpers.go
https://www.ietf.org/rfc/rfc4627.txt
https://github.com/rqlite/rqlite/issues/933
> Use correct MIME media type for JSON

- CHANGELOG.md
- go.mod
- go.sum
- log/log.go
- log/log_test.go
- store/store.go
bboltdb is the version the Consul now runs.
> Move to etcd's fork of BoltDB

- DOC/DATA_API.md
Add a missing column to an example API call.
> docs: add missing column

- cluster/client.go
Fix https://github.com/rqlite/rqlite/issues/1029
> Handle more connection errors

- CHANGELOG.md
- command/rewrite_test.go
- go.mod
- go.sum
Fix https://github.com/rqlite/rqlite/issues/1072
> Upgrade to latest SQL parser

- cluster/service.go
- http/service.go
- store/store.go
Error from remote node was being dropped.
> Fix remote-load error handling

- CHANGELOG.md
- cluster/bootstrap.go
- cluster/bootstrap_test.go
- cmd/rqlited/main.go
- system_test/cluster_test.go
It's the Store object that needs it.
> Bootstrapping doesn't need bootstrap-expect

- system_test/full_system_test.py
Address https://app.circleci.com/pipelines/github/rqlite/rqlite/2021/workflows/d7cee6c4-9dc1-45ad-af66-eb17622f9b13/jobs/9171?invite=true#step-109-111
> Ensure randomly selected addresses can't be reused

- CHANGELOG.md
- cmd/rqlited/flags.go
- cmd/rqlited/main.go
- store/store.go
https://github.com/rqlite/rqlite/issues/1132
> Stepdown as Leader before shutting down

- CHANGELOG.md
- cmd/rqlite/history/file.go
- cmd/rqlite/history/file_test.go
- cmd/rqlite/history/file_windows.go
- cmd/rqlite/history/paths.go
- cmd/rqlite/main.go
Fixes https://github.com/rqlite/rqlite/issues/1145.
> Delete history file if RQLITE_HISTFILESIZE is zero

- CHANGELOG.md
- go.mod
- go.sum
Pull in https://github.com/rqlite/rqlite-disco-clients/pull/12
> Upgrade disco client

- CHANGELOG.md
- db/db.go
- db/db_test.go
- http/request_parser.go
- http/request_parser_test.go
- system_test/single_node_test.go
https://github.com/rqlite/rqlite/issues/1177
> Fix parsing of nil named parameter values

- CHANGELOG.md
- store/store.go
https://github.com/rqlite/rqlite/issues/1217
> Check for more possible errors with peers

- CHANGELOG.md
- cmd/rqlited/main.go
- disco/service.go
Looks the 10x was a debug code.
> Reporting interval was too high

- CHANGELOG.md
- go.mod
- go.sum
Disco configs now support Environment variable expansion.
> Upgrade disco clients

- CHANGELOG.md
- cluster/client_test.go
- cmd/rqlited/main.go
> Reduce timeout for self-remove

- .gitignore
- CHANGELOG.md
- cluster/remove.go
- cluster/remove_test.go
- cmd/rqlited/main.go
- store/store.go
- store/store_test.go
> Refactor node self-removal

- CHANGELOG.md
- cluster/service.go
- cmd/rqlited/main.go
- store/store_test.go
May be solution to https://github.com/rqlite/rqlite/issues/1247.
> Proceed with DNS even if pre-existing state exists

- .circleci/config.yml
- CHANGELOG.md
- go.mod
- go.sum
- log/log.go
- log/log_test.go
- scripts/package.sh
https://github.com/rqlite/rqlite/issues/901
> Enable support for more architectures

- .circleci/config.yml
- .circleci/images/circleci-primary/Dockerfile
This will speed up builds, now that we're doing cross-compilation tests.
> Move to custom image for CircleCI

- system_test/e2e/auto_clustering.py
https://app.circleci.com/pipelines/github/rqlite/rqlite/2947/workflows/0cc343c8-83f3-415a-a652-7cccbc9904b3/jobs/15281
> Tweak test, remove raciness?

- CHANGELOG.md
- db/db.go
- db/db_inmem_test.go
- db/db_ondisk_test.go
> Add some WAL-related control code

- CHANGELOG.md
- snapshot/v2.go
- snapshot/v2_test.go
https://github.com/rqlite/rqlite/issues/1310
> Move to a newer proposal for V2 snapshot

- system_test/cluster_test.go
When running on Windows this test often encounters `ErrLeadershipLost`, at least in the AppVeyor CI environment. This means that INSERT may, or may not, be actually inserted into the SQLite database. As a result change this test to use explicit primary keys, so that if the records were actually inserted, the duplicate records will not be inserted (by also using the SQLite keyword `IGNORE`).
See https://github.com/rqlite/rqlite/issues/1123 for more information.
> Skip writes if records already in database

- CHANGELOG.md
- store/store.go
- store/store_inmem_test.go
This may be helpful for chunked-loads.
> Store can load from an io.Reader

- db/db.go
https://github.com/rqlite/rqlite/pull/1317#discussion_r1286866112
> Fix error checking

- CHANGELOG.md
- cmd/rqlited/flags.go
Fixes https://github.com/rqlite/rqlite/issues/1398
> Better logging of trailing flags

- CHANGELOG.md
- store/store.go
This will make it easier to swap new implementations in.
> Add an interface between Store and Snapshot Store

- CHANGELOG.md
- cmd/rqlite/main.go
- http/service.go
Fixes https://github.com/rqlite/rqlite/issues/1421
> Add mTLS support to rqlite CLI

- CHANGELOG.md
- http/nodes.go
> Use top-level timeout check for nodes/

- db/wal/compacting_scanner.go
GPT4 spotted this, which is ironic since it was GTP4 that wrote the code in the first place.
> No need to cast indices

- CHANGELOG.md
- http/query_params.go
- http/service.go
- http/service_test.go
Makes rest of HTTP code cleaner.
> Refactor query parameters into own code

- CHANGELOG.md
- cluster/service.go
- cmd/rqlited/main.go
- store/store.go
- store/store_test.go
- store/transport.go
- system_test/cluster_test.go
- system_test/helpers.go
- system_test/single_node_test.go
- tcp/mux.go
- tcp/mux_test.go
Don't hide the Dialing functionality inside a "Listener".
> Refactor internode networking implementation

- store/store.go
Obsolete functionality, which should have been deleted earlier.
> User snapshot channel not needed

- CHANGELOG.md
- cluster/bootstrap.go
- cmd/rqlited/main.go
- system_test/e2e/auto_clustering.py
https://github.com/rqlite/rqlite/issues/1545
> Don't hardcode suffrage when joining

- http/service.go
- store/store.go
Never really had a strong reason for it.
> Remove restriction on non-WAL restore

- aws/s3.go
Static AWS credentials make sense when you're running outside of AWS, but when you're running *inside* AWS, it's an operational smell.  Almost always the right thing to do is to use the role assigned to the environment where the workload is running, for example an EC2 role.  Or, for workloads deployed in AWS EKS, an [IRSA role](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).
The AWS SDK automatically does the right thing here when static credentials aren't specified.  If it's running in Kubernetes, it will use the K8s secret from the Service Account to authenticate itself to get an STS token.  Otherwise, it will try the EC2 IMDS (Instance Metadata Service) to fetch a token for the role assigned to the EC2 instance.
Or, even outside of AWS, it allows …
> Don't require static credentials for S3 access

- CHANGELOG.md
- system_test/e2e/multi_node.py
https://app.circleci.com/pipelines/github/rqlite/rqlite/4259/workflows/acd74c0c-3c91-4904-a037-183d1a99b118/jobs/36217
> Tighthen snapshot-join end-to-end testing

- CHANGELOG.md
- db/db.go
- db/state.go
- db/state_test.go
- system_test/e2e/helpers.py
- system_test/e2e/single_node.py
Because it's critical that the PRAGMA settings are correct, include an end-to-end test.
> Set Synchronous mode

- CHANGELOG.md
- cmd/rqlite/query.go
Fixes a panic in the rqlite shell.
> Don't stomp on outer error

- CHANGELOG.md
- db/db_common_test.go
- go.mod
- go.sum
> Upgrade to SQLite 3.45.0

- CHANGELOG.md
- http/service.go
https://github.com/rqlite/rqlite/issues/1628
> Improve Errors for internode comms failures

- CHANGELOG.md
- http/service.go
https://github.com/rqlite/rqlite/issues/1628
> Improve error when query on remote node fails

- CHANGELOG.md
- auto/backup/uploader_test.go
- store/store.go
The code is simpler and easier to read.
> Use atomic.Uint64 instead of mutexes for Store indexes

- CHANGELOG.md
- store/store.go
https://github.com/rqlite/rqlite/issues/1672
> Store is "not ready" during a Restore from Snapshot

- CHANGELOG.md
- command/encoding/json.go
- command/encoding/json_test.go
- http/query_params.go
- http/query_params_test.go
- http/service.go
- system_test/helpers.go
- system_test/single_node_test.go
https://github.com/rqlite/rqlite/issues/1691
> Support integer-array encoding of byte slices

- CHANGELOG.md
- log/log.go
- log/log_test.go
- store/state.go
- store/store.go
This code has served no real purpose since the 7.x series.
> Remove obsolete log info code

- CHANGELOG.md
- snapshot/sink.go
- snapshot/store.go
https://github.com/rqlite/rqlite/issues/1711
> Don't double-reap Snapshots

- CHANGELOG.md
- http/service.go
- queue/queue.go
- queue/queue_test.go
I may have other uses for this Queue in the future.
> Move Queue to use Generics

- CHANGELOG.md
- cluster/bootstrap.go
- cluster/bootstrap_test.go
- cluster/join.go
- cluster/join_test.go
- cmd/rqlited/main.go
- cmd/rqlited/signals.go
- system_test/cluster_test.go
- system_test/helpers.go
Fixes issue https://github.com/rqlite/rqlite/issues/1746
> Boot and Join should be cancelable

- CHANGELOG.md
- rsync/atomic.go
- rsync/cas.go
- rsync/cas_test.go
- store/store.go
- store/store_test.go
Help debug https://github.com/rqlite/rqlite/issues/1807
> Associate owners with CAS

- CHANGELOG.md
- rsync/cas.go
- rsync/cas_test.go
More work to help debug https://github.com/rqlite/rqlite/issues/1807
> More CAS logging

- CHANGELOG.md
- aws/s3.go
- aws/s3_test.go
- system_test/e2e/s3.py
https://github.com/rqlite/rqlite/issues/1833
> Fix AWS timestamped keys

- CHANGELOG.md
- cmd/rqlited/flags.go
- cmd/rqlited/main.go
- docker-entrypoint.sh
- extensions/store_test.go
See https://github.com/rqlite/helm-charts/issues/30
> Support multiple comma-delimited Extension paths

- CHANGELOG.md
- db/db.go
- db/db_checkpoint_test.go
- db/db_test.go
- db/state_test.go
This is to maximise compatibility with any external readers.
> Force creation of WAL files at open

- CHANGELOG.md
- rsync/cas.go
- rsync/cas_test.go
- store/store.go
May address https://app.circleci.com/pipelines/github/rqlite/rqlite/5551/workflows/65b1a968-4522-4043-88ae-075fd4162735/jobs/57176
> Don't Snapshot a closing Store

- CHANGELOG.md
- db/swappable_db.go
- store/store.go
- store/store_vacuum_test.go
> AutoVac should just VACUUM, not VACUUM INTO

- CHANGELOG.md
- store/store.go
Implement linearizable reads as described in section 6.4 of the [Raft dissertation](https://github.com/ongardie/dissertation/blob/master/online.pdf?raw=true).
> Correct implementation of linearizable reads

- CHANGELOG.md
- store/transport.go
Might address https://app.circleci.com/pipelines/github/rqlite/rqlite/5790/workflows/ccba13c4-d5a8-406d-946a-2ce48743d1d4/jobs/61286
> Explicitly close Raft network streams on shutdown

- http/service.go
https://github.com/rqlite/rqlite/issues/1971
> Skip and log stats that return error

- CHANGELOG.md
- cluster/join.go
- tcp/mux.go
Also help the end-user in another situation.
> Remove excessively concerning logging

- CHANGELOG.md
- http/nodes.go
- http/nodes_test.go
https://github.com/rqlite/rqlite/issues/2001
> Add version information to `/nodes` output

- CHANGELOG.md
- store/state.go
- store/store.go
- system_test/e2e/extensions.py
https://github.com/rqlite/rqlite/issues/2011
> Restore extensions when recovering node

- tools/rqbench.sh
- tools/rqlite.sh
- tools/rqlited.sh
Add a simple bash completion script for the client
Are you inclined to include these?
There are generators our there (including https://github.com/posener/complete) but this seems straightforward
> add bash completions

- CHANGELOG.md
- store/store.go
- system_test/cluster_test.go
- system_test/helpers.go
https://github.com/rqlite/rqlite/issues/2050
> Compress SQL-format backups during transmission
